version: "2"

run:
  build-tags:
    - tests

issues:
  max-same-issues: 30

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - goconst
    - gocritic
    - godot
    - goheader
    - gomoddirectives
    - gosec
    - importas
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usetesting
    - wastedassign
    - whitespace

  settings:
    exhaustive:
      default-signifies-exhaustive: true

    goheader:
      values:
        const:
          COMPANY: Zenauth Ltd.
      template: |-
        Copyright {{ YEAR-RANGE }} {{ COMPANY }}
        SPDX-License-Identifier: Apache-2.0

    govet:
      disable:
        - shadow
      enable-all: true

    nolintlint:
      require-specific: true
      allow-unused: false

    tagliatelle:
      case:
        rules:
          bson: goCamel
          json: goCamel
          xml: goCamel
          yaml: goCamel

  exclusions:
    generated: lax

    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

    rules:
      - linters:
          - forcetypeassert
          - goconst
          - govet
          - mnd
        path: _test\.go

      - linters:
          - errcheck
          - gocritic
        path: example_test\.go

    paths:
      - ^genpb/
      - ^hack/
      - ^tools/
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofumpt
    - goimports

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/cerbos/cerbos-sdk-go)
        - blank
        - dot
      custom-order: true

    gofumpt:
      extra-rules: true

  exclusions:
    generated: lax

    paths:
      - ^genpb/
      - ^hack/
      - ^tools/
      - third_party$
      - builtin$
      - examples$
