---
name: Pull Requests
on:
  pull_request:
    branches:
      - main
permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        go: ["1.25", "1.26"]
    name: Test on Go ${{ matrix.go }}
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Install just
        uses: cerbos/actions/install-tools@043c4c2f16da4bc1366f362cc41c288b8e48a3ae # main
        with:
          tools: just

      - name: Test
        env:
          CERBOS_HUB_API_ENDPOINT: "${{ secrets.CERBOS_HUB_API_ENDPOINT }}"
          CERBOS_HUB_CLIENT_ID: "${{ secrets.CERBOS_HUB_CLIENT_ID }}"
          CERBOS_HUB_CLIENT_SECRET: "${{ secrets.CERBOS_HUB_CLIENT_SECRET }}"
          CERBOS_HUB_STORE_ID: "${{ secrets.CERBOS_HUB_STORE_ID }}"
        run: just test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod

      - name: Install just
        uses: cerbos/actions/install-tools@043c4c2f16da4bc1366f362cc41c288b8e48a3ae # main
        with:
          tools: just

      - name: Tidy dependencies
        run: just deps

      - name: modernize
        run: just lint-modernize

      - name: golangci-lint
        uses: cerbos/actions/golangci-lint@043c4c2f16da4bc1366f362cc41c288b8e48a3ae # main
        with:
          args: "--config=.golangci.yaml -v"

      - name: Check repo status
        uses: cerbos/actions/check-repo-status@043c4c2f16da4bc1366f362cc41c288b8e48a3ae # main
